services:
  qemu:
    image: milou666/zerg-project
    container_name: zerg-project
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - WIN_ISO=/storage/windows.iso
      - STARCRAFT_ISO=/storage/starcraft.iso
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 5900:5900
      - 5700:5700
    volumes:
      - ./storage:/storage
    stop_grace_period: 2m
